### ISSUE TITLE
need link for file path in output channel

### ISSUE THREAD

**Issue by chen19901225** [appulate/vscode-file-watcher#10]
how to make path lie `./file_watcher/__main__.py:6:1:` to be clickable in output channel?

**Comment by listgarten100** [comment]
@chen19901225  Hello! We are considering this solution. But there is a problem in the vscode itself. More details can be read here https://github.com/microsoft/vscode/issues/586

**Comment by listgarten100** [comment]
Hi @chen19901225, please recheck with the new version 2.0.0.
