### ISSUE TITLE
[error] the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'

### ISSUE THREAD

**Issue by ThePlenkov** [appulate/vscode-file-watcher#12]
Hi!

I have a following settings file:

```
{
  "filewatcher.commands": [
    {
      "match": "\\.puml",
      "isAsync": true,
      "cmd": "docker run --rm -it  --mount type=bind,source=${workspaceRoot},target=/app theplenkov/plantuml-docker",
      "event": "onFileChange"
    }
  ]
}
```

when i try to create any *.puml file i have output like this:
```
[Event handled] ...
[onFileChange] for pattern "\.puml" started
[cmd] docker run --rm -it  --mount type=bind,source=c:\Users\pplenkov\Documents\git_projects\comments-service,target=/app theplenkov/plantuml-docker
[error] the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
```

Do you have any ideas why?

The command is working properly if input directly into CLI

**Comment by VovanNet** [comment]
Try to quote target param like target='/app theplenkov/plantuml-docker'. Space is delimeter for windows cmd line

**Comment by ThePlenkov** [comment]
but space is in the correct position. theplenkov/plantuml-docker - is the name of the image, not the target.

**Comment by ThePlenkov** [comment]
it was just -t issue with docker command. I kept just -i. So all good!
