### ISSUE TITLE
VSCode prints error with usage of screeps-typescript-starter execution

### ISSUE THREAD

**Issue by mlostekk** [appulate/vscode-file-watcher#14]
When setting up a file watcher with this repo (https://github.com/screepers/screeps-typescript-starter), it prints `[error]` in two lines, and VSCode there were some errors.

Here is the output

![Bildschirmfoto 2021-10-15 um 13 12 35](https://user-images.githubusercontent.com/10534316/137478782-a5a1f7c1-954b-4b5a-82d1-04c2d748506e.png)

This is the code for the settings:

```
...
    "filewatcher.commands": [
        {
            "match": "\/Users\/mlostek\/Projects\/screeps\/my\/src\/.*",
            "isAsync": true,
            "cmd": "(cd ${workspaceRoot}; npm run push-main)",
            "event": "onFileChange"
        }
    ]
...
```

When i execute the command `npm run push-main` in a terminal, no error occurs.

![Bildschirmfoto 2021-10-15 um 13 15 06](https://user-images.githubusercontent.com/10534316/137478757-f3213f29-35f5-4084-aefc-6eeaf04ffa1a.png)

Any idea how to fix that?

(crosspost to the screeps template repo https://github.com/screepers/screeps-typescript-starter/issues/161)

**Comment by listgarten100** [comment]
@mlostekk Hello! Check out the new plugin update 1.1.7v. If your issue has not been covered, be sure to write to us. Thank you.
