### ISSUE TITLE
Possible to change dir ?

### ISSUE THREAD

**Issue by wiryonolau** [appulate/vscode-file-watcher#17]
Is it possible to change target directory 

```
workspaceRoot:      d:\projects\foo-proj
file:               d:\projects\foo-proj\src\app\app.component.ts
fileBasename:       app.component.ts
fileBasenameNoExt:  app.component
fileExtname:        ts
fileDirname:        d:\projects\foo-proj\src\app
```

I need to change the src to dist
```
d:\projects\foo-proj\src\app\app.component.ts
d:\projects\foo-proj\dist\app\app.component.ts
```

**Comment by listgarten100** [comment]
@wiryonolau Hello! You can do this directly in the execution file. Placeholders are associated with files that trigger events. Thanks for your issue.

**Comment by theking2** [comment]
I'm tracking a file `composer.json` and want to execute `composer dump-autoload` in the folder containing that file.

**Comment by listgarten100** [comment]
@theking2 if you have several files with the same name in the workspace, then you can specify a specific path to the file. Since"match" is a Regex, and also in a JSON string backslashes have to be double escaped such as when targetting folders. 
```
 "filewatcher.commands": [
    {
      "match": "CspTest\\\\vendor\\\\theking2\\\\csp-builder\\\\composer\\.json$",
      "cmd": "composer dump-autoload",
      "event": "onFileChange",
      "isAsync": true, 
    }
  ],
```
if you have one file with this name in the workspace, or if you need it to work for each such file, then you can do this:
```
 "filewatcher.commands": [
    {
      "match": "composer\\.json$",
      "cmd": "composer dump-autoload",
      "event": "onFileChange",
      "isAsync": true, 
    }
  ],
```

**Comment by theking2** [comment]
That looks promising. Composer will create a myriad of composer json files so if i stick to the first version how do I make sure the command is run in the proper working directory?

**Comment by listgarten100** [comment]
@theking2 use placeholders fot that (more info in Readme.md):
![image](https://user-images.githubusercontent.com/73188490/228921032-f1093706-1629-4bd1-b230-eeaf955732ab.png)

**Comment by still-dreaming-1** [comment]
I think what they mean is, whatever command is run, they want to choose which directory the "cmd" is run from, they want to set the current working directory. I have this same need. Those placeholders are not the easiest way to run the command from the desired working directory. What directory are onFileChange commands even run from? Shouldn't they be run from the workspace root? It doesn't seem like that is the case. There is a missing "cwd" option and it's unclear what the default is.

**Comment by bandtank** [comment]
I have the same question and issue. The instructions are not clear about this at all unfortunately.
