### ISSUE TITLE
onFolderChange doesn't work as expected under Linux (mint 20.3)

### ISSUE THREAD

**Issue by nicolasmol** [appulate/vscode-file-watcher#19]
It does not detect file creation/deletion an behave just like onFileChange
For renaming...I don't know since, only developing Flutter, flutter extension already covers renaming

**Comment by listgarten100** [comment]
@nicolasmol  Hello! Check version 1.1.7 please, we have added new events. More details in the README

**Comment by nicolasmol** [comment]
@listgarten100 onFolderChange doesn't seem to cover "onFolderRename".
Renaming a folder doesn't trigger FileWatcher

**Comment by listgarten100** [comment]
@nicolasmol answered here https://github.com/appulate/vscode-file-watcher/issues/26#issuecomment-1305599561
