### ISSUE TITLE
У вас расширение работает не в DEV режиме?

### ISSUE THREAD

**Issue by nodkz** [appulate/vscode-file-watcher#2]
У вас расширение работает не в DEV режиме?

У меня ничего в консоль не сыпет по стандартному примеру.
Встроенные команды `extension.enableFileWatcher` тоже не работаю. При вызове "File watcher: enable" пишет "command 'extension.enableFileWatcher' not found".

**Comment by nodkz** [comment]
Поискал альтернативные плагины – ничего вменяемого не нашел.

Ваш вотчер может стать достаточно популярным плагином. Туча лет вс-коду, а такой тулзени из коробки нет и вынуждает всех писать свои экстэншены.

**Comment by VovanNet** [comment]
Должно работать как есть, правда тестили на винде в основном. пришлите конфигурацию вашего окружения

**Comment by VovanNet** [comment]
Возможную проблему обнаружили, завтра будет апдейт

**Comment by VovanNet** [comment]
@nodkz проверьте текущую версию

**Comment by nodkz** [comment]
Спасибо огромное! 👍
Все заработало под MacOS!

Я его заюзал, чтобы рестартить apollographql.vscode-apollo, когда схема обновляется. Вот такие изменения в setting.json
```
  "filewatcher.commands": [
    {
      "match": "\\.graphql*",
      "isAsync": true,
      "cmd": "touch ${workspaceRoot}/apps/admin/apollo.config.js",
      "event": "onFileChange"
    }
  ]
```

Если хотите еще донавернуть либу, то можно прикрутить вызов встроенной команды, которые используются для кейбиндингов и комманд других плагинов. Тогда точно всех порвете! Типа:
```
  "filewatcher.commands": [
    {
      "match": "\\.graphql*",
      "isAsync": true,
      "vsCommand": "apollographql/reloadService",
      "event": "onFileChange"
    }
  ]
```

Т.е. вместо `touch`, который у меня работает. Я бы воспользовался внутренним вызовом нотификации https://github.com/apollographql/apollo-tooling/blob/master/packages/apollo-language-server/src/server.ts#L215

**Comment by nodkz** [comment]
Немного промо для вашего плагина 😉
https://github.com/apollographql/apollo-tooling/issues/1685
