### ISSUE TITLE
Suggestion for a shorter text for cluttered status bar

### ISSUE THREAD

**Issue by nicolasmol** [appulate/vscode-file-watcher#23]
Hi
My suggestion is that in status-bar, you replace any "File Watcher" by this` $(telescope)`
![image](https://user-images.githubusercontent.com/61077647/199794122-31e7b79d-3687-46c1-a43d-3ba6448e6079.png)

**Comment by listgarten100** [comment]
Thank you for your advice, we will consider your suggestion.

**Comment by listgarten100** [comment]
@nicolasmol hi, recheck version 2.0.0, we added telescope icon. Thanks)
