### ISSUE TITLE
Status bar color go wrong

### ISSUE THREAD

**Issue by Philofallever** [appulate/vscode-file-watcher#24]
after update to 1.16,  status bar color is white
![image](https://user-images.githubusercontent.com/15180187/199879784-6e0590fc-3c41-4fbb-b9d4-13a9fc3078bd.png)

version 1.1.6
theme : solarized-light

**Comment by listgarten100** [comment]
Thank you for your vigilance, we will fix it soon.

**Comment by listgarten100** [comment]
@Philofallever Hi! This issue was fixe in 1.1.7v. In the next release, we plan to give the ability to customize the color of the text in the status bar.

**Comment by Philofallever** [comment]
fixed, thx
