### ISSUE TITLE
Commands not being executed

### ISSUE THREAD

**Issue by ericanderson91** [appulate/vscode-file-watcher#25]
Hello, my team ran into an issue with a recent update where our commands were outputting to the console but not actually being executed.  After a little digging it seems like `this.execOption` getter was resulting in `{"shell": ""}` which does not allow exec to run (at least on our MacBooks).

I ran the extension locally and was able to resolve this issue with by changing line 115 (file-watcher.ts) like so:
<img width="739" alt="image" src="https://user-images.githubusercontent.com/95306299/200055340-0eef0e78-34d5-4b28-80a9-6613179010f0.png">

Alternatively I could set the global "filewatcher.shell" setting to something (e.g. "/bin/bash" and it started working again) but that's listed as an optional property in the docs.

Also our configuration used to be like the following, but the shell can no longer be set per command. This is not important to us, but may worth noting in case it affects others users.

`"filewatcher.commands": [
    {
        "shell": "/bin/bash",
        "match": "\\.js|\\.scss|\\.json|\\.html|\\.css",
        "isAsync": false,
        "cmd": "echo '${file} changed'",
        "event": "onFileChange"
    }
],`

Happy to take a stab at a PR for this but you guys may have a better fix than my hack noted above.

**Comment by RogerBetter** [comment]
exact same problem here.

**Comment by listgarten100** [comment]
@ericanderson91 @RogerBetter Hi! This issue was fixed in 1.1.7v, please check it. Regarding the execution of the shell for each command - this feature was not present in earlier versions. But thanks for the sensible suggestion, most likely in future versions we will take it into service.

**Comment by RogerBetter** [comment]
> @ericanderson91 @RogerBetter Hi! This issue was fixed in 1.1.7v, please check it. Regarding the execution of the shell for each command - this feature was not present in earlier versions. But thanks for the sensible suggestion, most likely in future versions we will take it into service.

Yeap! It works again! This plugin is my magic solution for many problems. Thanks for your work!

**Comment by ericanderson91** [comment]
Looks to be fixed for me as well! Thank you for addressing it so quickly!

**Comment by listgarten100** [comment]
@ericanderson91 hi, please recheck version 2.0.0, now can be set per command shell.
