### ISSUE TITLE
Multiroot workspace path problems

### ISSUE THREAD

**Issue by agreedSkiing** [appulate/vscode-file-watcher#28]
Hi,
I have a multi folder workspace project setup in a WSL2 ubuntu that has some problems when trying to detect a filechange in another workspace folder.

The folders in the json below uses the vscode workspace base path as standard which is '/home/user/' and I tried to change the path to an absolute path from /home/ but then my workspace doesn’t work anymore ☹.
```json
{
  "folders": [
    {
      "path": "repos/domain-backend"
    },
    {
      "path": "repos/domain-frontend"
    },
    {
      "path": "repos/domain-generator"
    },
    {
      "path": "repos/domain-signer"
    },
    {
      "path": "repos/domain-publisher"
    },
    {
      "path": "repos/other-backend"
    },
    {
      "path": "repos/other-frontend"
    }
  ],
  "settings": {
    "filewatcher.commands": [
      {
        "match": ".*\/com\/company\/domain\/.*.java",
        "isAsync": true,
        "cmd": "echo workspaceRoot=${workspaceRoot} \n workspaceRelativeDir=${workspaceRelativeDir} \n file=${file} \n fileOld=${fileOld} \n fileBasename=${fileBasename} \n fileDirname=${fileDirname} \n fileExtname=${fileExtname} \n fileBasenameNoExt=${fileBasenameNoExt}",
        "event": "onFileChange"
      },
    ]
  },
  "extensions": {
    "recommendations": []
  }
}
```
So, to the problem/issue. When the filewatcher executes on a change it bases the workspaceRoot on the top folder in folders array instead of the current working folder and the workspaceRelativeDir starts with ../ instead of /src/.

**Output of the echo command**
```bash
[cmd] echo workspaceRoot=/home/user/repos/domain-backend
 workspaceRelativeDir=../domain-signer/src/main/java/com/company/domain/signer/endpoints/SignerResource.java 
 file=/home/user/repos/domain-signer/src/main/java/com/company/domain/signer/endpoints/SignerResource.java 
 fileOld= 
 fileBasename=SignerResource.java 
 fileDirname=/home/user/repos/domain-signer/src/main/java/com/company/domain/signer/endpoints 
 fileExtname=.java 
 fileBasenameNoExt=SignerResource
workspaceRoot=/home/user/repos/domain-backend
```
If i instead execute it from the top folder in the previous json the echo looks like this
```bash
[cmd] echo workspaceRoot=/home/user/repos/domain-backend 
 workspaceRelativeDir=src/main/java/com/company/domain/backend/db/LocalDateConverter.java 
 file=/home/user/repos/domain-backend/src/main/java/com/company/domain/backend/db/LocalDateConverter.java 
 fileOld= 
 fileBasename=LocalDateConverter.java 
 fileDirname=/home/user/repos/domain-backend/src/main/java/com/company/domain/backend/db 
 fileExtname=.java 
 fileBasenameNoExt=LocalDateConverter
workspaceRoot=/home/user/repos/domain-backend
```

**Comment by listgarten100** [comment]
@agreedSkiing Hello, thanks for your issue. We do indeed have a "workspaceRoot" - looks at the first element of the "folders" array. "workspaceRelativeDir" - calculates the path relative to the first workspace. But now there is a "currentWorkspace" pattern that gives the actual current workspace, it just wasn't mentioned in the Readme, but it works. In the next release, we'll fix Readme.md and add a pattern like "currentRelativeWorkspace" that will be calculated relative to the current workspace. I will let you know when we release a new version, thanks again.

**Comment by listgarten100** [comment]
Hi @agreedSkiing, please recheck this issue with the new version 2.0.0.

**Comment by agreedSkiing** [comment]
@listgarten100 works great with 2.0.0 with the help of currentRelativeWorkspace
