### ISSUE TITLE
it can't monitor remote peer to update the file content

### ISSUE THREAD

**Issue by shenxiaolong-code** [appulate/vscode-file-watcher#30]
I log in machines A and B.

I update file X on machine A ( which is run the gdb debugger, the file X is updated by gdb command) , 
I  expect to monitor file X on machine B (which is running vscode), but the extension don't work as expected.

BTW, the extension works for the below scenario:
I update file X on A machine and monitor file X on machine A.

but it still has an issue:
if I only:  "cmd": "echo '${file} file content Changed'",
it works.

if I call script :  "cmd": "source '/home/xiaolongs/linuxScript/vscode/bin/vscode_open_file_goto_line.csh'",
it will report below error:
[error] /bin/sh: 1: source: not found
-- it seems it always uses the bash shell and not the related setting page. ( I am using the tcsh shell )

if I call script : "cmd": "tcsh '/home/xiaolongs/linuxScript/vscode/bin/vscode_open_file_goto_line.csh'",
it will report below error:
[error] TERM environment variable not set.

**Comment by listgarten100** [comment]
@shenxiaolong-code hi, can i see your settings for filewatcher?
