### ISSUE TITLE
code-workspace

### ISSUE THREAD

**Issue by theking2** [appulate/vscode-file-watcher#34]
I have this in my code-workspace, but it seems not picked up by file watcher:
```js
	"settings": {
		"filewatcher.commands": [
			{
				"watch": "CspTest/vendor/theking2/csp-builder/composer.json",
				"cmd": "composer dump-autoload",
				"event": "onFileChange",
				"isAsync": true,
				
			}
		]
	},
```

is this correct here?

**Comment by listgarten100** [comment]
hi @theking2, try this commad settings, for exapmple (match must be a required property): 
`  "filewatcher.commands": [
    {
      "match": "^(?!.*@).*\\.ts$",
      "isAsync": true,
      "cmd": "cd '${workspaceRoot}'; node ./index.js '${file}'",
      "event": "onFileChange"
    },
]`
