### ISSUE TITLE
onFolderChange running "vscodeTask" as "cmd"

### ISSUE THREAD

**Issue by still-dreaming-1** [appulate/vscode-file-watcher#39]
Hello. Thanks for making this extension.

I'm getting the following error output:
```
[Event handled] ...
[onFolderChange] for pattern "\.*" started
[vscode-task] gen-inits
[error] Error: command 'gen-inits' not found
[onFolderChange] for pattern "\.*" finished
```

**Context:**

I have the following VSCode setting defined:

```
{
  "match": "\\.*",
  "isAsync": true,
  "vscodeTask": "gen-inits",
  "event": "onFolderChange",
}
```

I have a `gen-inits` VSCode task defined, like so:

```
{
  "label": "gen-inits",
  "type": "shell",
  "command": "python ./scripts/gen_inits.py",
}
```

I am able to run the task through VSCode the normal way, but when it gets triggered from the event, I get the error output at the top. The error makes it sound like perhaps it is trying to run it as a cmd instead of a task.

Also, the `onFolderChange` event is getting triggered twice, just from saving my workspace file, even if I didn't actually make any changes. The strange thing is, it is not triggering any of the file events. I mean, from my perspective it doesn't seem like it should be triggering any events, because I didn't actually change anything. But if anything, I would expect it to trigger a file event, not a folder event.

**Comment by listgarten100** [comment]
@still-dreaming-1 Hello. Thank you for your request. In the VSCode setting to start the process from tasks.json you need to add an array of strings in the "vscodeTask" like this: `
"vscodeTask": ["workbench.action.tasks.runTask", "gen-inits"]
`
You can also try using the "onFileChange" event by extending the file matching area with match.
This should help.

**Comment by still-dreaming-1** [comment]
It works perfect that way, thanks!
