### ISSUE TITLE
External folder\file

### ISSUE THREAD

**Issue by de-Bat** [appulate/vscode-file-watcher#40]
Hi,
Does this extension support watching files or folder that resides outside the workspace? I tried several solutions but with no success.
Thanks,
Ron

**Comment by listgarten100** [comment]
@de-Bat Hi, try using the "onFileChangeImmediate" event, it might help. When changing files using Git, it works great (but at the same time, the Vscode must be open). Perhaps it will cover your needs too. Thanks for the issue.
