### ISSUE TITLE
onFolderChange run match against the *file* that changed and not the *folder*

### ISSUE THREAD

**Issue by tsaodown** [appulate/vscode-file-watcher#5]
I want to run tasks based on whether a specific type of file was created or deleted. The way that `onFolderChange` is implemented now means that I can only run tasks based on changes at the folder level. Is this a possible changee>

**Comment by tsaodown** [comment]
It does seem that the [VSCode FileSystemWatcher API](https://code.visualstudio.com/api/references/vscode-api#FileSystemWatcher) supports `onDidCreate` and `onDidDelete` events. Maybe we could hook into those to detect file deletion and creation, match regex against triggering files, and then running commands based on that. I could take a crack and the PR if you want me to.

**Comment by listgarten100** [comment]
@tsaodown  Hello! Check version 1.1.7 please, we have added new events. More details in the README.
