### ISSUE TITLE
"shell" setting should expect a string value, not a number

### ISSUE THREAD

**Issue by Tazaf** [appulate/vscode-file-watcher#8]
Hi !

There seems to be an issue with the expected type of the `shell` setting.

Trying to set the shell to `/bin/bash` instead of the default `/bin/sh` using the GUI is not possible, as the input field does not accept string (initially, the value of the field was `0`):

![image](https://user-images.githubusercontent.com/7702322/80463553-b2410180-8938-11ea-84b9-a0c3e60f6383.png)
> "The value should be a number"

This same message is displayed when setting the value in the `settings.json`:
![image](https://user-images.githubusercontent.com/7702322/80463628-d4d31a80-8938-11ea-97e4-b4d4f7271366.png)

Altough, in this case, saving the `settings.json` file **is possible**, in which case the `shell` value **is properly used** by the extension.

Still, it should be acceptable to set a string value for this setting, as a number doesn't make any sense here.

**Comment by listgarten100** [comment]
@Tazaf Hi! This issue fixed in 1.1.7v, please check it. Happy codding.
